@section('title', (!empty($seoWebsite)) ? $seoWebsite['title'] : 'Danh muc san pham')
@section('keywords', (!empty($seoWebsite)) ? $seoWebsite['keywords'] : 'Keywords')
@section('description', (!empty($seoWebsite)) ? $seoWebsite['description'] : 'description')
@section('og-title', (!empty($seoWebsite)) ? $seoWebsite['og-title'] : 'Danh muc san pham')
@section('og-image', (!empty($seoWebsite)) ? $seoWebsite['og-image'] : 'og-image')
@section('og-url', route('home.contact'))
@section('og-site_name', (!empty($seoWebsite)) ? $seoWebsite['og-site_name'] : 'og-site_name')
@section('od-description', (!empty($seoWebsite)) ? $seoWebsite['od-description'] : 'od-description')
@section('twitter-title', (!empty($seoWebsite)) ? $seoWebsite['twitter-title'] : 'twitter-title')
@section('twitter-image', (!empty($seoWebsite)) ? $seoWebsite['twitter-image'] : 'twitter-image')
@section('twitter-url', route('home.contact'))
@section('twitter-card', (!empty($seoWebsite)) ? $seoWebsite['twitter-card'] : 'twitter-card')